InpCODIGOCH         'id=reservation'
InpAPELLIDOSCH      'id=lastName'
BtnLoginCH          'xpath=//input[@value='Buscar']'
CHKPASAJEROSCH      'xpath=(//label[contains(.,'Hacer Check-in')])[XXX]'
BtnContinuarCH      'id=btn_8464'